version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/shift-manager
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/fetch_secrets.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop_app.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      runas: root
